set number
set relativenumber
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent
set ignorecase
set smartcase
set cursorline
set clipboard="unnamedplus"
set noswapfile

set scrolloff=5

set incsearch

map Q gq

nnoremap <silent> <C-j> :m .+1<CR>==
nnoremap <silent> <C-k> :m .-2<CR>==
inoremap <silent> <C-j> <Esc>:m .+1<CR>==gi
inoremap <silent> <C-k> <Esc>:m .-2<CR>==gi
vnoremap <silent> <C-j> :m '>+1<CR>gv=gv
vnoremap <silent> <C-k> :m '<-2<CR>gv=gv

" Initialize Vim-Plug
call plug#begin('~/.vim/plugged')  " On Unix/Linux/macOS
" call plug#begin('~/vimfiles/plugged')  " On Windows  

" Highlight copied text
Plug 'machakann/vim-highlightedyank'
" Commentary plugin (use IntelliJ's built-in commenting instead)
Plug 'tpope/vim-commentary'
Plug 'ajmwagar/ideavim-easymotion'
Plug 'tpope/vim-surround'          " Add/change/delete surroundings (quotes, brackets, etc.)
Plug 'airblade/vim-gitgutter'      " Show Git diff signs in the gutter
Plug 'preservim/nerdtree'          " File explorer (may not work fully in IdeaVim)
Plug 'TheBlob42/idea-which-key'

" Finalize plugin setup
call plug#end()
